import type { SourceReviewItem } from "../schemas";

export const demoSourceReviewItems: SourceReviewItem[] = [
  {
    id: "source-review-business-creation",
    title: "MonEntreprise.bj - création d'entreprise",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "APIEx, République du Bénin",
    candidateUrl: "https://monentreprise.bj/informer",
    status: "verified",
    priority: "high",
    relatedProcedureSlugs: ["creation-entreprise", "rccm"],
    notes: [
      "Source connectée manuellement le 2026-05-19 : guide, processus, coûts/délais, pièces et certificats.",
      "Revue encore partielle : ne pas généraliser les pièces d'établissement à toutes les formes juridiques.",
      "Prochaine action : créer une table de claims par forme juridique.",
    ],
    lastReviewedAt: "2026-05-19",
  },
  {
    id: "source-review-citizenship",
    title: "Casier judiciaire sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Portail du Numérique / Portail National des Services Publics",
    candidateUrl: "https://service-public.bj/public/services/service/PS00373",
    status: "verified",
    priority: "high",
    relatedProcedureSlugs: ["casier-judiciaire"],
    notes: [
      "Service, coût, délai annoncé et pièces principales extraits le 2026-05-30 depuis l'API publique service-public.bj.",
      "DossierBJ garde une réserve de revérification avant paiement car le délai peut varier en cas de forte demande.",
      "Ne pas importer de données personnelles ni de fichiers utilisateur.",
    ],
    lastReviewedAt: "2026-05-30",
  },
  {
    id: "source-review-rccm",
    title: "Extrait RCCM sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Portail du Numérique / Portail National des Services Publics",
    candidateUrl: "https://service-public.bj/public/services/service/PS00024",
    status: "verified",
    priority: "high",
    relatedProcedureSlugs: ["rccm"],
    notes: [
      "Service, coût, délai et pièces extraits le 2026-05-30 depuis l'API publique service-public.bj.",
      "Le service en ligne indique aucune pièce nécessaire ; le présentiel demande copie RCCM et quittance.",
      "Ne pas réutiliser les coûts de création d'entreprise pour l'extrait RCCM.",
    ],
    lastReviewedAt: "2026-05-30",
  },
  {
    id: "source-review-civil-status",
    title: "CIP sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Agence Nationale d’Identification des Personnes",
    candidateUrl: "https://service-public.bj/public/services/service/PS00392",
    status: "verified",
    priority: "medium",
    relatedProcedureSlugs: ["certificat-identification-personnelle"],
    notes: [
      "Service, coût, délai et pièces extraits le 2026-05-30 depuis l'API publique service-public.bj.",
      "La fiche distingue CIP pour nationaux et CIPR pour résidents étrangers.",
      "Ne pas collecter d'actes d'état civil dans le MVP.",
    ],
    lastReviewedAt: "2026-05-30",
  },
  {
    id: "source-review-administrative-certificate",
    title: "Attestation de régularité fiscale foncière sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Direction Générale des Impôts",
    candidateUrl: "https://service-public.bj/public/services/service/PS01512",
    status: "verified",
    priority: "medium",
    relatedProcedureSlugs: ["attestation-regularite-fiscale-fonciere"],
    notes: [
      "Service, coût gratuit, délai de 72 heures, public et pièces extraits le 2026-05-30 depuis l'API publique service-public.bj.",
      "La quittance citée doit être interprétée avec prudence : le service est indiqué gratuit, mais le demandeur doit être à jour fiscalement.",
      "Ne pas importer de documents fiscaux ou fonciers personnels.",
    ],
    lastReviewedAt: "2026-05-30",
  },
  {
    id: "source-review-ao-radar-gouv-bj",
    title: "Marchés publics sur gouv.bj",
    module: "AO Radar",
    country: "BJ",
    authority: "Gouvernement de la République du Bénin",
    candidateUrl: "https://www.gouv.bj/opportunites/marches-publics/",
    status: "needs_human_review",
    priority: "medium",
    relatedProcedureSlugs: [],
    notes: [
      "Page officielle repérée pour alimenter le pilote AO Radar sans scraping agressif.",
      "Les opportunités pilotes restent à revérifier avant toute réponse commerciale.",
      "Utiliser ce registre uniquement comme point d'entrée vers la source officielle.",
    ],
    lastReviewedAt: "2026-05-30",
  },
];
