import type { SourceReviewItem } from "../schemas";

export const demoSourceReviewItems: SourceReviewItem[] = [
  {
    id: "source-review-business-creation",
    title: "MonEntreprise.bj - création d'entreprise",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "APIEx, République du Bénin",
    candidateUrl: "https://monentreprise.bj/informer",
    status: "verified",
    priority: "high",
    relatedProcedureSlugs: ["creation-entreprise", "rccm"],
    notes: [
      "Source connectée manuellement le 2026-05-19 : guide, processus, coûts/délais, pièces et certificats.",
      "Revue encore partielle : ne pas généraliser les pièces d'établissement à toutes les formes juridiques.",
      "Prochaine action : créer une table de claims par forme juridique.",
    ],
    lastReviewedAt: "2026-05-19",
  },
  {
    id: "source-review-citizenship",
    title: "Casier judiciaire sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Portail du Numérique / Portail National des Services Publics",
    candidateUrl: "https://service-public.bj/public/services/service/PS00373",
    status: "needs_human_review",
    priority: "high",
    relatedProcedureSlugs: ["casier-judiciaire"],
    notes: [
      "Service et URL confirmés via le Portail du Numérique.",
      "À extraire manuellement : frais, délai actuel, pièces exactes et étapes du formulaire.",
      "Ne pas importer de données personnelles ni de fichiers utilisateur.",
    ],
    lastReviewedAt: "2026-05-19",
  },
  {
    id: "source-review-rccm",
    title: "Extrait RCCM sur service-public.bj",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Portail du Numérique / Portail National des Services Publics",
    candidateUrl: "https://service-public.bj/public/services/service/PS00024",
    status: "needs_human_review",
    priority: "high",
    relatedProcedureSlugs: ["rccm"],
    notes: [
      "Service repéré sur le Portail du Numérique.",
      "À extraire manuellement : critères de demande, frais, délai, pièces et support.",
      "Ne pas réutiliser les coûts de création d'entreprise pour l'extrait RCCM.",
    ],
    lastReviewedAt: "2026-05-19",
  },
  {
    id: "source-review-civil-status",
    title: "Sources état civil",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Institution officielle à confirmer",
    candidateUrl: "https://example.org/dossierbj-demo/source-etat-civil",
    status: "to_connect",
    priority: "medium",
    relatedProcedureSlugs: ["document-etat-civil"],
    notes: [
      "Identifier une source officielle avant tout détail de pièces, frais ou délai.",
      "Ne pas collecter d'actes d'état civil dans le MVP.",
    ],
  },
  {
    id: "source-review-administrative-certificate",
    title: "Source pour attestations administratives",
    module: "DossierBJ Core",
    country: "BJ",
    authority: "Institution officielle à confirmer",
    candidateUrl: "https://example.org/dossierbj-demo/source-attestation",
    status: "to_connect",
    priority: "medium",
    relatedProcedureSlugs: ["attestation-administrative"],
    notes: [
      "Identifier l'autorité compétente avant de créer une fiche vérifiée.",
      "Ne pas déduire les pièces à fournir depuis des exemples non officiels.",
    ],
  },
];
